### ISSUE TITLE
bwrap: Can't mkdir parents for /app/usr/lib/sdk/llvm12: Read-only file system

### ISSUE THREAD

**Issue by travier** [flathub/org.freedesktop.Sdk.Extension.llvm12#16]
Hi maintainers!

Since a few days ago, we are starting to have issues running applications that depend on this extension for a yet unknown reason:

```
bwrap: Can't mkdir parents for /app/usr/lib/sdk/llvm12: Read-only file system
error: ldconfig failed, exit status 256
```

As this happens in bubblewrap, this is before the application start and is thus unexpected.

See https://github.com/flathub/org.kde.kdevelop/issues/9.

Any ideas about how we might diagnose the issue are appreciated!

Thanks for the work on this extension!

**Comment by Erick555** [comment]
[This part](https://github.com/flathub/org.kde.kdevelop/blob/master/org.kde.kdevelop.json#L5-L10) of kdevelop manifest is suspicious to me. Please try removing it and test app again.

llvm12 is runtime extension but above line may trick flatpak it's app extension therefore bwrap try to mount it under /app.

**Comment by travier** [comment]
Thanks, I'll give it a try.

**Comment by Erick555** [comment]
I confirmed this fixes it locally:

1. If extension **is in manifest** and **is installed** then running kdevlop fails
2. If extension **is in manifest** and **isn't installed** then running kdevlop succeeds
3. If extension **is not** in manifest and **is installed** then running kdevlop succeeds and extension is still mounted under /usr/lib/sdk/llvm12

So considering above the problem was hidden until you install extension and try running kdevelop. Removing mentioned part of manifest should fix the problem and all functionality will still be there.

**Comment by Erick555** [comment]
BTW: if the goal is to autodownload llvm12 extension during app install in order to ensure users will have it installed you may change above manifest part like this instead of removing it:
```
    "add-extensions": {
        "org.freedesktop.Sdk.Extension.llvm12": {
            "no-autodownload": "false",
            "version": "21.08"
        }
    },
```
Users would still need an [extra step](https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm12#debuggingdevelopment) to activate it though unless you set  `--env=PATH=/app/bin:/usr/bin:/usr/lib/sdk/llvm12/bin` permission in manifest.

**Comment by travier** [comment]
Great! Thanks a lot for the help!

**Comment by travier** [comment]
Closing this one as I'll track progress on this in the KDevelop tracker. Thanks!
